title: Capstone Documentation
description: Documentation for the Networking Capstone Project
theme: just-the-docs
color_scheme: dark

url: https://digtrx.github.io

aux_links:
  Template Repository: https://github.com/digtrx/digtrx.github.io
